### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by indrajit447**
Signed-off-by: indrajit447 <naskarindrajit557@gmail.com>

### CODE REVIEW

**Review by Debarghya001 — CHANGES_REQUESTED** [review]
This a wrong format u have used

**Review by Subhradeep10 — DISMISSED** [review]
Will change it

**Comment by indrajit447** [comment]
> Will change it

That's what i am saying

**Review by Debarghya001 — APPROVED** [review]

**Review by Debarghya001 — APPROVED** [review]

**Comment by Debarghya001** [comment]
`

**Pull request closed without merging**
